[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
talent_olympics_dao_voting = "5KqPscmVdEYJ9HmQdymcBvpfi515debCGUmpgoH6sEn4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
